base/urls.py
from django.conf.urls import patterns, include, url
from base import views


urlpatterns = patterns('',
    url(r'^$', views.home),
    url(r'^post/create/$', views.create_post,name="create_post"),
    url(r'^message/create/$', views.send_message,name="send_message"),
)

bogrim/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'base.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^base/', include('base.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^admin/', include(admin.site.urls)),
) 
    

base/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from utils import get_icon_path
# user = User.objects.create_user('john', 'lennon@thebeatles.com', 'johnpassword')

class BaseLink(models.Model):
    description = link = models.CharField(max_length=50)
    link = models.CharField(max_length=250)


class Category(models.Model):
    name = models.CharField(unique=True, max_length=100)
    tags = TaggableManager()
    icon = models.ImageField(upload_to=get_icon_path)
    
    def __unicode__(self):
        return u'%s'%(self.name)
    
    def icon_thumbnail(self):
        return '<img src="%s"/>' %self.icon.url 
    icon_thumbnail.allow_tags = True
    
class BaseMessage(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    sender = models.ForeignKey(User, related_name="sender_user")
    content = models.TextField()

class Post(BaseMessage):
    title = models.CharField(max_length=50)
    last_modified = models.DateTimeField(auto_now=True)
    tags = TaggableManager()
    categories = models.ManyToManyField(Category)

class UserMessage(BaseMessage):
    title = models.CharField(max_length=50)
    receiver = models.ForeignKey(User, related_name="reciver_user")

class PostLink(BaseLink):
    post = models.ForeignKey(Post)

base/forms.py
from base.models import Post, UserMessage
from django.forms import ModelForm

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'tags', 'categories', 'sender', 'content']
        
class UserMessageForm(ModelForm):
    class Meta:
        model = UserMessage
        fields = ['title', 'receiver', 'content', 'sender']

base/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from base.forms import PostForm, UserMessageForm
from base.models import Category, Post
from django.core.urlresolvers import reverse
import json

def home(request):
    category_list = Category.objects.all()
    post_list = Post.objects.all()
    ctx = {
        "categories":category_list,
        "posts":post_list
    }
    return render(request, 'home.html', ctx)

def create_post(request):
    if not request.user.is_authenticated():
            return HttpResponseRedirect(reverse('login') + "?next=create_post")
    if request.method == 'POST': # If the form has been submitted...
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            post_form.save()
            return HttpResponseRedirect(reverse('home'))
    else:
        post_form = PostForm()
    category_list = Category.objects.all()
    ctx = {
        "form":post_form,
        "categories":category_list
    }
    return render(request, 'base/post.html', ctx)

def send_message(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('login'))
    message = {"status":"0", "error":""}
    if request.method == 'POST':
        message_form = UserMessageForm(request.POST)
        if message_form.is_valid():
            message_form.save()
            message['status'] = 1
        else:
            message['status'] = 1
            message['errors'] = form.errors
    else:
        message['status'] = 0
        message['errors'] = 'Hacking is bad for you!'
    simplejson = json.dumps(message)
    return HttpResponse(simplejson, content_type='application/json')

templates/base/message_modal.html
<div class="modal fade" data-backdrop="static" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="Send message" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-keyboard="false" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">ערוך פרופיל</h4>
        <p class="error hide" id="errors"></p>
      </div>
      <div class="modal-body">
       <form id="messageForm">
       	<article class="form-group">
			<label for="reciever">ל:</label>
			<input type="text" id="messageReceiver" name="receiver" class="form-control" data-user-id="" readonly="readonly" value="d" />
		</article>
		<article class="form-group">
			<label for="messageTitle"></label>
			<input type="text" id="messageTitle" name="title" class="form-control" value="d" />
		</article>
       	<article class="form-group">
			<label for="first_name">הודעה:</label>
			<textarea type="text" rows="6" class="form-control" name="message" id="userMessage"></textarea>
		</article>
      </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">בטל</button>
        <button type="button" class="btn btn-primary">שלח</button>
      </div>
    </div>
  </div>
</div>

templates/base/message_script.html
{# <script> #}

function resetMessageForm() {
	$('#errors').html('').addClass('hide');
	$('#userMessage').html('');
}


$('.post-owner').click(function(){
	var elem = $(this);
	var message_form = $('#messageForm');
	var receiver =  message_form.find('#messageReceiver');
	var title = message_form.find('#messageTitle');
	receiver.val(elem.data('user-name'));
	receiver.data('user-id', elem.data('user-id'));
	title.attr("readonly","readonly");
	if(elem.data('resource-id')){
		title.val(elem.data('resource-value'));
	}
})

$('#messageModal .btn-primary').click(function(){
	var message_form = $('#messageModal');
	var message = message_form.find('#userMessage').val();
	var receiver =  message_form.find('#messageReceiver').data('user-id');
	var title = message_form.find('#messageTitle').val();
	if(!message){
		$('#errors').html('ההודה אינה יכולה להשלח ריקה').removeClass('hide');
		return;
	}
	$.ajax({  
		type: "POST",  
		url: '{% url "send_message" %}',
		data: { 
				'content':message,
				'title':title,
				'receiver':receiver,
				'sender':'{{ user.id }}',
			 	'csrfmiddlewaretoken':$('input[name="csrfmiddlewaretoken"]').val() 
			  },  
		success:function(data){
			if(data['status']){
				if(data['errors']){
					$('#errors').html(jQuery.parseJSON(data['errors'])).removeClass('hide');
					return;
				}
				else{
					$('#messageModal').modal("hide");
					resetMessageForm();
				}
			}	
			else{
				$('#errors').html(data['errors']).removeClass('hide');
			} 
		}
	});
	
	
	
});

$('#messageModal .btn-default').click(function(){
	resetMessageForm();
});

templates/base/post.html
{% extends "base.html" %}
{% block body %}
<div class="create-post">
	<section class="errors">
	{% if form.errors %}
		{{ form.errors }}
	{% endif %}	
	</section>
	<form action="{% url 'create_post' %}" class="row" method="post">
			{% csrf_token %}
				<div class="form-group col-md-2">
					<label>כותרת:</label>
					<input id="id_title" class="form-control" maxlength="50 form-control" name="title" type="text">
				</div>
				<div class="form-group col-md-4">
					<label>תוכן:</label>
					<textarea id="id_content" class="form-control" name="content" ></textarea>
				</div>
				<div class="form-group col-md-2">
					<label>תגיות:</label>
					<input id="id_tags" class="form-control" name="tags" type="text">
				</div>

				<div class="form-group col-md-2">
					<label>קטגוריות:</label>
					<select multiple="multiple" class="form-control" id="id_categories" name="categories">
						{% for c in categories %}
						<option value="{{ c.id }}">{{ c.name }}</option>
						{% endfor %}
					</select>
				</div>
				<input type="hidden" value="{{ user.id }}" name="sender" />
				<div class="btn-wrapper">
				<button type="submit" class="btn btn-info col-md-2">המשך!</button>
				</div>
			</form>
	
	
</div>
{% endblock %}